"""empty message

Revision ID: 48cd3a33fe17
Revises: 4a6591c8f1dd
Create Date: 2022-06-08 08:14:59.647446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48cd3a33fe17'
down_revision = '4a6591c8f1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
